# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "minitest", "~> 5.0"
  gem "rake", "~> 13.0"
  gem "webmock", "~> 3.0"
  gem "rbs-inline", "~> 0.10"
  gem "steep", "~> 1.9"
end
