[book]
title = "API Reference"
authors = ["Chris Corbyn"]
description = "HTTP API reference Zizq — The lightweight job queue server"
language = "en"
src = "src"

[build]
build-dir = "../../target/docs/api"

[output.html]
site-url = "/docs/api/"
additional-css = ["src/zizq_docs.css"]
default-theme = "light"
preferred-dark-theme = "light"

[output.html.print]
enable = false
